package vista;

import com.formdev.flatlaf.FlatLightLaf;
import dao.daoServicios;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.List;
import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import modelo.Servicios;

/**
 *
 * @author Nelson
 */
public class clienteServicios extends javax.swing.JPanel {

    /**
     * Creates new form clienteServicios
     */
    public clienteServicios() {
        FlatLightLaf.setup();
        initComponents();
        mostrarServiciosEnScrollPanel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Scroll = new guiRecursos.GuiJScrollPane();
        contentServ = new javax.swing.JPanel();

        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Servicios");
        Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 400, 40));

        Scroll.setBorder(null);

        javax.swing.GroupLayout contentServLayout = new javax.swing.GroupLayout(contentServ);
        contentServ.setLayout(contentServLayout);
        contentServLayout.setHorizontalGroup(
            contentServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        contentServLayout.setVerticalGroup(
            contentServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        Scroll.setViewportView(contentServ);

        Panel.add(Scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 890, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void mostrarServiciosEnScrollPanel() {
        daoServicios daoServ = new daoServicios();
        List<Servicios> servicios = daoServ.obtenerServicios();

        int numColumnas = 3;
        int velocidadScroll = 16;

        // Agrega un espaciado entre paneles en el GridLayout
        int hgap = 20; // Espaciado horizontal
        int vgap = 20; // Espaciado vertical
        contentServ.setLayout(new GridLayout(0, numColumnas, hgap, vgap));

        for (Servicios servicio : servicios) {
            DropShadowPanel servicioPanel = new DropShadowPanel(5); // Cambia el valor según el tamaño de sombra que desees
            servicioPanel.setLayout(new BorderLayout());
            servicioPanel.setPreferredSize(new Dimension(200, 280));

            DropShadowPanel cuadroPanel = new DropShadowPanel(5); // Cambia el valor según el tamaño de sombra que desees
            cuadroPanel.setLayout(new BoxLayout(cuadroPanel, BoxLayout.Y_AXIS));
            cuadroPanel.setPreferredSize(new Dimension(180, 250));

            cuadroPanel.setBorder(BorderFactory.createLineBorder(Color.GRAY, 2, true));


            JPanel contenidoPanel = new JPanel();
            contenidoPanel.setLayout(new BoxLayout(contenidoPanel, BoxLayout.Y_AXIS));
            contenidoPanel.add(Box.createRigidArea(new Dimension(0, 10)));
            
            //Añadir Titulo
            JLabel nameLabel = new JLabel(servicio.getNombre_servicio());
            nameLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
            nameLabel.setFont(new Font("SansSerif", Font.BOLD, 16));
            contenidoPanel.add(nameLabel);

            contenidoPanel.add(Box.createRigidArea(new Dimension(0, 10)));
            
            String imagePath = "/images/servicios/" + servicio.getNombre_servicio() + ".png";
            URL imageURL = getClass().getResource(imagePath);
            ImageIcon icon;

            if (imageURL != null) {
                icon = new ImageIcon(imageURL);
            } else {
                // Si la imagen no existe, utiliza la imagen predeterminada.
                icon = new ImageIcon(getClass().getResource("/images/servicios/defaultService.png"));
            }
            
            Image image = icon.getImage().getScaledInstance(150, -1, Image.SCALE_SMOOTH);
            icon = new ImageIcon(image);
            JLabel imageLabel = new JLabel(icon);
            imageLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
            contenidoPanel.add(imageLabel);

            contenidoPanel.add(Box.createRigidArea(new Dimension(0, 10)));
            
            JPanel descPanel = new JPanel();
            descPanel.setLayout(new BorderLayout());

            JTextPane descText = new JTextPane();
            descText.setBorder(null);
            descText.setText(servicio.getDescripcion());
            descText.setEditable(false);

            // Configura el fondo transparente
            descText.setBackground(new Color(0, 0, 0, 0));

            // Configura los márgenes internos para agregar espacio en los lados
            int margenLados = 15;
            SimpleAttributeSet attributes = new SimpleAttributeSet();
            StyleConstants.setLeftIndent(attributes, margenLados);
            StyleConstants.setRightIndent(attributes, margenLados);
            StyledDocument doc = descText.getStyledDocument();
            doc.setParagraphAttributes(0, doc.getLength(), attributes, false);

            descText.setHighlighter(null);
            descText.setEditable(false);
            descText.setFocusable(false);
            
            descPanel.add(descText, BorderLayout.CENTER);
            contenidoPanel.add(descPanel);
            
            JButton button = new JButton("Revisar servicio");
            button.setAlignmentX(Component.CENTER_ALIGNMENT);

            // Agrega un ActionListener al botón para manejar el clic
            button.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    irOfertas(servicio);
                }
            });

            contenidoPanel.add(button);

            JPanel buttonPanel = new JPanel();
            buttonPanel.setLayout(new FlowLayout(FlowLayout.CENTER));
            contenidoPanel.add(button);
            
            contenidoPanel.add(Box.createRigidArea(new Dimension(0, 10)));
            
            cuadroPanel.add(Box.createVerticalGlue());
            cuadroPanel.add(contenidoPanel);
            cuadroPanel.add(buttonPanel);

            servicioPanel.add(Box.createHorizontalGlue(), BorderLayout.CENTER);
            servicioPanel.add(cuadroPanel, BorderLayout.CENTER);

            contentServ.add(servicioPanel);
        }

        contentServ.revalidate();
        Scroll.getVerticalScrollBar().setUnitIncrement(velocidadScroll);
    }
    
    public class DropShadowPanel extends JPanel {

        private static final long serialVersionUID = 1L;

        public int pixels;

        public DropShadowPanel(int pix) {
            this.pixels = pix;
            Border border = BorderFactory.createEmptyBorder(pixels, pixels, pixels, pixels);
            this.setBorder(BorderFactory.createCompoundBorder(this.getBorder(), border));
            this.setLayout(new BorderLayout());
        }

        @Override
        protected void paintComponent(Graphics g) {
            int shade = 0;
            int topOpacity = 80;
            for (int i = 0; i < pixels; i++) {
                g.setColor(new Color(shade, shade, shade, ((topOpacity / pixels) * i)));
                g.drawRect(i, i, this.getWidth() - ((i * 2) + 1), this.getHeight() - ((i * 2) + 1));
            }
        }
    }

    public void irOfertas(Servicios serv){
        MostrarPanel(new clienteVerServicio(serv));
    }
    
    public void MostrarPanel(JPanel panel){
        panel.setSize(951, 610);
        panel.setLocation(0,0);
        this.removeAll();
        this.add(panel, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private guiRecursos.GuiJScrollPane Scroll;
    private javax.swing.JPanel contentServ;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
