package vista;

import com.formdev.flatlaf.FlatLightLaf;
import dao.daoServicios;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelo.DetalleTrabajador;
import modelo.Servicios;

/**
 *
 * @author Nelson
 */
public class clienteVerServicio extends javax.swing.JPanel {
    Servicios serv;
    
    daoServicios daoServ = new daoServicios();
    /**
     * Creates new form clienteServicios
     */
    public clienteVerServicio(Servicios serv) {
        initComponents();
        FlatLightLaf.setup();
        
        this.serv = serv;
        ServicioImagenIniciar();
        textoServicio();
        System.out.println("contar trabajadores = "+daoServ.contarTrabajadoresPorServicio(serv.getId()));
        muestra();
    }
    
void muestra() {
    DefaultTableModel dt = (DefaultTableModel) tablaInfo.getModel();
    dt.setRowCount(0);

    for (DetalleTrabajador detTra : daoServ.obtenerDetallesTrabajadoresPorServicio(serv.getId())) {
        Object v[] = { detTra.getIdTrabajador(), detTra.getNombreTrabajador(), detTra.getCalificacion() };
        dt.addRow(v);
    }

    // Establecer un renderizador personalizado para la columna 2 (suponiendo que es indexada en 0)
    tablaInfo.getColumnModel().getColumn(2).setCellRenderer(new StarRenderer());
}
    

// Clase de renderizador personalizado para mostrar estrellas
class StarRenderer extends DefaultTableCellRenderer {
    private final ImageIcon ICONO_ESTRELLA = new ImageIcon(getClass().getResource("/images/icon/star.png"));

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

        // Verificar si la columna es la que deseas personalizar
        if (column == 2 && value instanceof Number) {
            int calificacion = ((Number) value).intValue();

            // Establecer el texto con estrellas según el valor de calificacion
            setText(String.valueOf(calificacion));

            // Ajustar el tamaño del ícono al tamaño de la celda
            int alturaCelda = table.getRowHeight(row);
            ImageIcon iconoRedimensionado = new ImageIcon(ICONO_ESTRELLA.getImage().getScaledInstance(alturaCelda, alturaCelda, java.awt.Image.SCALE_SMOOTH));
            setIcon(iconoRedimensionado);
        }

        return c;
    }
}

    public void textoServicio(){
        tituloServ.setText(serv.getNombre_servicio());
        descServ.setText(serv.getDescripcion());
        numTrabaj.setText(String.valueOf(daoServ.contarTrabajadoresPorServicio(serv.getId())));
        
    }
    
    public void ServicioImagenIniciar(){
        String imagePath = "/images/servicios/" + serv.getNombre_servicio() + ".png";
        URL imageURL = getClass().getResource(imagePath);
        ImageIcon icon;

        if (imageURL != null) {
            icon = new ImageIcon(imageURL);
        } else {
            // Si la imagen no existe, utiliza la imagen predeterminada.
            icon = new ImageIcon(getClass().getResource("/images/servicios/defaultService.png"));
        }
        
        Image image = icon.getImage().getScaledInstance(200, -1, Image.SCALE_SMOOTH);
        icon = new ImageIcon(image);
        imgServ.setIcon(icon);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        imgServ = new javax.swing.JLabel();
        tituloServ = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        descServ = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        numTrabaj = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cstmButon1 = new guiRecursos.cstmButon();
        tituloServ1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaInfo = new javax.swing.JTable();

        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Servicio Info");
        Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgServ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(imgServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 240, 150));

        tituloServ.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloServ.setText("Default");
        jPanel1.add(tituloServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 580, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 580, 10));

        descServ.setBackground(new Color(0, 0, 0, 0));
        descServ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descServ.setText("Defalt");
        descServ.setToolTipText("");
        jScrollPane1.setViewportView(descServ);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 580, 70));

        jLabel2.setText("Actualmente hay");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 100, -1));

        numTrabaj.setForeground(new java.awt.Color(36, 40, 44));
        numTrabaj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numTrabaj.setText("0");
        jPanel1.add(numTrabaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 20, -1));

        jLabel4.setText("trabajadores disponibles para este servicio");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 250, -1));

        Panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 890, 230));

        cstmButon1.setForeground(java.awt.Color.white);
        cstmButon1.setText("Volver");
        cstmButon1.setBorderColor(null);
        cstmButon1.setColor(new java.awt.Color(102, 102, 102));
        cstmButon1.setColorClick(new java.awt.Color(204, 204, 204));
        cstmButon1.setColorOver(new java.awt.Color(153, 153, 153));
        cstmButon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cstmButon1ActionPerformed(evt);
            }
        });
        Panel.add(cstmButon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 80, -1));

        tituloServ1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloServ1.setText("Trabajadores disponibles");
        Panel.add(tituloServ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 290, 30));

        tablaInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "Nombre", "Calificacion  Promedio"
            }
        ));
        jScrollPane2.setViewportView(tablaInfo);
        if (tablaInfo.getColumnModel().getColumnCount() > 0) {
            tablaInfo.getColumnModel().getColumn(0).setMaxWidth(100);
            tablaInfo.getColumnModel().getColumn(1).setMaxWidth(500);
            tablaInfo.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        Panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 540, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cstmButon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cstmButon1ActionPerformed
        MostrarPanel(new clienteServicios());
    }//GEN-LAST:event_cstmButon1ActionPerformed

        public void imageIconCambiar(URL resource, JLabel iconoMod, int tamaño) {
        if (resource != null) {
            ImageIcon iconLogo = new ImageIcon(resource);
            Image image = iconLogo.getImage();
            Image imgRescalado = image.getScaledInstance(tamaño, tamaño, java.awt.Image.SCALE_SMOOTH);
            iconLogo = new ImageIcon(imgRescalado);
            iconoMod.setIcon(iconLogo);
        } else {
            System.out.println("No se encontro");
        }
    }
    
    
    public void MostrarPanel(JPanel panel){
        panel.setSize(951, 610);
        panel.setLocation(0,0);
        this.removeAll();
        this.add(panel, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private guiRecursos.cstmButon cstmButon1;
    private javax.swing.JTextPane descServ;
    private javax.swing.JLabel imgServ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel numTrabaj;
    private javax.swing.JTable tablaInfo;
    private javax.swing.JLabel tituloServ;
    private javax.swing.JLabel tituloServ1;
    // End of variables declaration//GEN-END:variables
}
