package vista;

import guiRecursos.CustomFont;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
/**
 *
 * @author Nelson
 */
public class frmElegirTipo extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistroTipo
     */
    public frmElegirTipo() {
        FlatLightLaf.setup();
        initComponents();
        Font subTitulo = CustomFont.loadCustomAnotherFont(24f);
        lblCliente.setFont(subTitulo);
        lblTrabajador.setFont(subTitulo);
        
        tituloAnimado();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraVentana1 = new guiRecursos.GuiBarraVentana();
        jPanel1 = new javax.swing.JPanel();
        tituloElegir = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        imgTrabajador = new javax.swing.JLabel();
        imgCliente = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblTrabajador = new javax.swing.JLabel();
        btnRegTrabajador = new javax.swing.JButton();
        btnRegCliente = new javax.swing.JButton();
        lblVolver = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        tituloElegir.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        tituloElegir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgTrabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/elegirTrabajador.png"))); // NOI18N
        jPanel2.add(imgTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 160, 160));

        imgCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/elegirCliente.png"))); // NOI18N
        jPanel2.add(imgCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 160, 160));

        lblCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCliente.setText("Cliente");
        jPanel2.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 160, 30));

        lblTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrabajador.setText("Trabajador");
        jPanel2.add(lblTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 160, 30));

        btnRegTrabajador.setText("Registrar como Trabajador");
        btnRegTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegTrabajadorActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 180, 30));

        btnRegCliente.setText("Registrar como Cliente");
        btnRegCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 180, 30));

        lblVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblVolver.setForeground(new java.awt.Color(82, 88, 126));
        lblVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVolver.setText("Volver a Login");
        lblVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVolverMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblVolverMousePressed(evt);
            }
        });
        jPanel2.add(lblVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 130, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tituloElegir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tituloElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraVentana1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraVentana1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegTrabajadorActionPerformed
        frmRegTrabajador regT = new frmRegTrabajador();
        regT.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegTrabajadorActionPerformed

    private void lblVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseEntered
        lblVolver.setForeground(new Color(82, 128, 234));
    }//GEN-LAST:event_lblVolverMouseEntered

    private void lblVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseExited
        lblVolver.setForeground(new Color(82,88,126));
    }//GEN-LAST:event_lblVolverMouseExited

    private void lblVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMousePressed
        frmLogin login = new frmLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblVolverMousePressed

    private void btnRegClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegClienteActionPerformed
        frmRegCliente regC= new frmRegCliente();
        regC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmElegirTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmElegirTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmElegirTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmElegirTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmElegirTipo().setVisible(true);
            }
        });
    }

    public void tituloAnimado(){
        Font anotherfont = CustomFont.loadCustomAnotherFont(36f);
        if (anotherfont != null) {
            tituloElegir.setFont(anotherfont);
        }
        
        // Texto que deseas mostrar
        final String textoCompleto = "¿Que tipo de Usuario Registrar?";
        final int delay = 20; // Intervalo en milisegundos entre letras

        Timer timer = new Timer(delay, new ActionListener() {
            int index = 0;

            @Override
            public void actionPerformed(ActionEvent e) {
                if (index < textoCompleto.length()) {
                    tituloElegir.setText(textoCompleto.substring(0, index + 1));
                    index++;
                } else {
                    ((Timer) e.getSource()).stop(); // Detener el temporizador cuando se haya mostrado todo el texto
                }
            }
        });

        timer.start();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private guiRecursos.GuiBarraVentana barraVentana1;
    private javax.swing.JButton btnRegCliente;
    private javax.swing.JButton btnRegTrabajador;
    private javax.swing.JLabel imgCliente;
    private javax.swing.JLabel imgTrabajador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblTrabajador;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JLabel tituloElegir;
    // End of variables declaration//GEN-END:variables
}
