package guiRecursos;

import java.awt.Font;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Nelson
 */
public class GuiBarraVentana extends javax.swing.JPanel {
    Font minecraftFont = CustomFont.loadMinecraftFont();
    
    
    public GuiBarraVentana() {
        initComponents();
        // Utiliza el ClassLoader para cargar el recurso
        imageIconCambiar(getClass().getClassLoader().getResource("images/icono.png"), iconImg, 20);
    }
    
    public void imageIconCambiar(URL resource, JLabel iconoMod, int tamaño) {
        if (resource != null) {
            ImageIcon iconLogo = new ImageIcon(resource);
            Image image = iconLogo.getImage();
            Image imgRescalado = image.getScaledInstance(tamaño, tamaño, java.awt.Image.SCALE_SMOOTH);
            iconLogo = new ImageIcon(imgRescalado);
            iconoMod.setIcon(iconLogo);
        } else {
            System.out.println("No se encontro");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        barraInfo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        iconImg = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JPanel();
        minbtn = new javax.swing.JPanel();
        btnMin = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JPanel();
        exitbtn = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(580, 28));

        contenedor.setPreferredSize(new java.awt.Dimension(580, 28));
        contenedor.setLayout(new javax.swing.BoxLayout(contenedor, javax.swing.BoxLayout.X_AXIS));

        barraInfo.setBackground(new java.awt.Color(51, 51, 51));
        barraInfo.setPreferredSize(new java.awt.Dimension(150, 28));
        barraInfo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraInfoMouseDragged(evt);
            }
        });
        barraInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraInfoMousePressed(evt);
            }
        });
        barraInfo.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        titulo.setFont(minecraftFont.deriveFont(12f));
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Titulo por Defecto");
        titulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        barraInfo.add(jPanel1);
        jPanel1.setBounds(30, 0, 340, 30);

        iconImg.setForeground(new java.awt.Color(255, 255, 255));
        iconImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconImg.setPreferredSize(new java.awt.Dimension(21, 28));
        barraInfo.add(iconImg);
        iconImg.setBounds(0, 0, 30, 28);

        contenedor.add(barraInfo);

        btnMinimizar.setBackground(new java.awt.Color(89, 89, 89));
        btnMinimizar.setMaximumSize(new java.awt.Dimension(28, 28));
        btnMinimizar.setPreferredSize(new java.awt.Dimension(28, 28));
        btnMinimizar.setLayout(new javax.swing.BoxLayout(btnMinimizar, javax.swing.BoxLayout.LINE_AXIS));

        minbtn.setBackground(new java.awt.Color(89, 89, 89));

        btnMin.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnMin.setForeground(new java.awt.Color(255, 255, 255));
        btnMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMin.setText("_");
        btnMin.setToolTipText("");
        btnMin.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMinMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout minbtnLayout = new javax.swing.GroupLayout(minbtn);
        minbtn.setLayout(minbtnLayout);
        minbtnLayout.setHorizontalGroup(
            minbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMin, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        minbtnLayout.setVerticalGroup(
            minbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        btnMinimizar.add(minbtn);

        contenedor.add(btnMinimizar);

        btnCerrar.setBackground(new java.awt.Color(89, 89, 89));
        btnCerrar.setMaximumSize(new java.awt.Dimension(28, 28));
        btnCerrar.setPreferredSize(new java.awt.Dimension(28, 28));
        btnCerrar.setLayout(new javax.swing.BoxLayout(btnCerrar, javax.swing.BoxLayout.LINE_AXIS));

        exitbtn.setBackground(new java.awt.Color(89, 89, 89));

        btnExit.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("X");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitbtnLayout = new javax.swing.GroupLayout(exitbtn);
        exitbtn.setLayout(exitbtnLayout);
        exitbtnLayout.setHorizontalGroup(
            exitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        exitbtnLayout.setVerticalGroup(
            exitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        btnCerrar.add(exitbtn);

        contenedor.add(btnCerrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    boolean dentroMouse = false;
    private void btnMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseClicked
        /*if (dentroMouse) {
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(BarraVentana.this);
            frame.setExtendedState(JFrame.ICONIFIED);
        }*/
    }//GEN-LAST:event_btnMinMouseClicked

    private void btnMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseEntered
        minbtn.setBackground(new java.awt.Color(120,120,120));
        dentroMouse = true;
    }//GEN-LAST:event_btnMinMouseEntered

    private void btnMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseExited
        minbtn.setBackground(new java.awt.Color(89,89,89));
        dentroMouse = false;
    }//GEN-LAST:event_btnMinMouseExited

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        exitbtn.setBackground(new java.awt.Color(211,77,77));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        exitbtn.setBackground(new java.awt.Color(89,89,89));
    }//GEN-LAST:event_btnExitMouseExited
    
    int xMouse = 0, yMouse = 0;  
    private void barraInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraInfoMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_barraInfoMousePressed

    private void barraInfoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraInfoMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(GuiBarraVentana.this);
        frame.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_barraInfoMouseDragged

    private void btnMinMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseReleased
        if (dentroMouse) {
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(GuiBarraVentana.this);
            frame.setExtendedState(JFrame.ICONIFIED);
        }
    }//GEN-LAST:event_btnMinMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraInfo;
    private javax.swing.JPanel btnCerrar;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnMin;
    private javax.swing.JPanel btnMinimizar;
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel exitbtn;
    private javax.swing.JLabel iconImg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel minbtn;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    public void setTitulo(String nomTitulo) {
        this.titulo.setText(nomTitulo);
    }
}
