package guiRecursos;

import java.awt.Color;

/**
 *
 * @author Nelson
 */
public class GuibotonPanel extends javax.swing.JPanel {
    Color normalColor = new Color(52, 73, 94);
    /**
     * Creates new form botonPanel
     */
    public GuibotonPanel() {
        initComponents();
        this.setBackground(normalColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTexto = new javax.swing.JLabel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        btnTexto.setForeground(new java.awt.Color(204, 204, 204));
        btnTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTexto.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.setBackground(new Color(133, 146, 158));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.setBackground(normalColor);
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnTexto;
    // End of variables declaration//GEN-END:variables

    //private Color colorText = new Color (253, 254, 254);
    
    public void setjLabel1(String nombreBoton) {
        this.btnTexto.setText(nombreBoton);
    }

    public static int[] obtenerNumerosDesdeCadena(String cadena) {
        String[] partes = cadena.split(",");
        int[] numeros = new int[partes.length];
        
        for (int i = 0; i < partes.length; i++) {
            try {
                numeros[i] = Integer.parseInt(partes[i]);
            } catch (NumberFormatException e) {
                // Manejar el error si alguna parte no es un número válido
                numeros[i] = 0; // Por ejemplo, asignar un valor por defecto
            }
        }
        
        return numeros;
    }
}
