package guiRecursos;

import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Nelson
 */
public class GuimenuBoton extends javax.swing.JPanel {

    /**
     * Creates new form menuBoton
     */
    public GuimenuBoton() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconSeccion = new javax.swing.JLabel();
        txtSeccion = new javax.swing.JLabel();

        setBackground(new java.awt.Color(65, 67, 73));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        iconSeccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtSeccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSeccion.setForeground(new java.awt.Color(255, 255, 255));
        txtSeccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtSeccion.setText("Section");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSeccion, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconSeccion, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(txtSeccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.setBackground(new Color(108, 113, 122));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.setBackground(new Color(65, 67, 73));
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconSeccion;
    private javax.swing.JLabel txtSeccion;
    // End of variables declaration//GEN-END:variables
    
    public void iconImg(String iconImagen){
        imageIconCambiar(getClass().getClassLoader().getResource("images/icon/"+iconImagen), iconSeccion, 40);
    }
    public void textoSeccion(String seccion){
        this.txtSeccion.setText(seccion);
    }
    
    public void imageIconCambiar(URL resource, JLabel iconoMod, int tamaño) {
        if (resource != null) {
            ImageIcon iconLogo = new ImageIcon(resource);
            Image image = iconLogo.getImage();
            Image imgRescalado = image.getScaledInstance(tamaño, tamaño, java.awt.Image.SCALE_SMOOTH);
            iconLogo = new ImageIcon(imgRescalado);
            iconoMod.setIcon(iconLogo);
        } else {
            System.out.println("No se encontro");
        }
    }
}
